-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bd_medico
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_medico
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_medico` DEFAULT CHARACTER SET UTF8MB4;
USE `bd_medico` ;

-- -----------------------------------------------------
-- Table `bd_medico`.`POBLACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`POBLACION` (
  `IDPOBLACION` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_POBLACION` VARCHAR(50) NOT NULL COMMENT 'NOMBRE DE LA POBLACION',
  PRIMARY KEY (`IDPOBLACION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`MUNICIPIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`MUNICIPIO` (
  `IDMUNICIPIO` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_MUNICIPIO` VARCHAR(50) NOT NULL COMMENT 'NOMBRE DEL MUNICIPIO',
  PRIMARY KEY (`IDMUNICIPIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`ESTADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`ESTADO` (
  `IDESTADO` INT NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA TABLA',
  `NOMBRE_ESTADO` VARCHAR(30) NOT NULL COMMENT 'NOMBRE DEL ESTADO',
  PRIMARY KEY (`IDESTADO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`OCUPACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`OCUPACION` (
  `IDOCUPACION` INT NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA TABLA',
  `NOMBRE_OCUPACION` VARCHAR(50) NOT NULL COMMENT 'OCUPACION',
  PRIMARY KEY (`IDOCUPACION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`TIPO_PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`TIPO_PACIENTE` (
  `IDTIPO_PACIENTE` INT NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA TABLA',
  `TIPO_PACIENTE` VARCHAR(20) NOT NULL COMMENT 'TIPO DEL PACIENTE, A=ASEGURADO, P=PARTICULAR',
  PRIMARY KEY (`IDTIPO_PACIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`COLONIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`COLONIA` (
  `IDCOLONIA` INT NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA TABLA',
  `NOMBRE_COLONIA` VARCHAR(100) NOT NULL COMMENT 'NOMBRE DE LA COLONIA',
  PRIMARY KEY (`IDCOLONIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`PACIENTE` (
  `IDPACIENTE` INT NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA',
  `NOMBRES` VARCHAR(30) NOT NULL COMMENT 'NOMBRES DEL PACIENTE',
  `APATERNO` VARCHAR(20) NOT NULL COMMENT 'APELLIDO PATERNO',
  `AMATERNO` VARCHAR(20) NOT NULL COMMENT 'APELLIDO MATERNO',
  `CALLE` VARCHAR(100) NOT NULL COMMENT 'CALLE',
  `NUMERO` INT NOT NULL COMMENT 'NUMERO EXTERIOR',
  `FECHA_NACIMIENTO` DATE NOT NULL DEFAULT '1900-01-01' COMMENT 'FECHA DE NACIMIENTO',
  `TEL_FIJO` VARCHAR(10) NULL COMMENT 'TELEFONO FIJO',
  `TEL_TRABAJO` VARCHAR(10) NULL COMMENT 'TELEFONO DEL TRABAJO',
  `TEL_CELULAR` VARCHAR(10) NOT NULL COMMENT 'TELEFONO CELULAR',
  `SEXO` CHAR(1) NOT NULL COMMENT 'SEXO, M=MASCULINO, F=FEMENINO',
  `EMAIL` VARCHAR(100) NULL DEFAULT 'correo@algo.com' COMMENT 'CORREO ELECTRONICO',
  `RFC` VARCHAR(13) NULL DEFAULT 'ALGO000000XXX' COMMENT 'RFC',
  `FECHA_ALTA` DATE NOT NULL COMMENT 'FECHA DE ALTA COMO PACIENTE DEL MEDICO',
  `ESTATUS` CHAR(1) NOT NULL DEFAULT 'A' COMMENT 'ESTATUS DEL PACIENTE, A=ACTIVO, I=INACTIVO',
  `IDPOBLACION` INT NOT NULL,
  `IDMUNICIPIO` INT NOT NULL,
  `IDESTADO` INT NOT NULL,
  `IDOCUPACION` INT NOT NULL,
  `IDTIPO_PACIENTE` INT NOT NULL,
  `IDCOLONIA` INT NOT NULL,
  PRIMARY KEY (`IDPACIENTE`),
  INDEX `fk_PACIENTE_POBLACION1_idx` (`IDPOBLACION` ASC),
  INDEX `fk_PACIENTE_MUNICIPIO1_idx` (`IDMUNICIPIO` ASC),
  INDEX `fk_PACIENTE_ESTADO1_idx` (`IDESTADO` ASC),
  INDEX `fk_PACIENTE_OCUPACION1_idx` (`IDOCUPACION` ASC),
  INDEX `fk_PACIENTE_TIPO_PACIENTE1_idx` (`IDTIPO_PACIENTE` ASC),
  INDEX `fk_PACIENTE_COLONIA1_idx` (`IDCOLONIA` ASC),
  CONSTRAINT `fk_PACIENTE_POBLACION1`
    FOREIGN KEY (`IDPOBLACION`)
    REFERENCES `bd_medico`.`POBLACION` (`IDPOBLACION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_MUNICIPIO1`
    FOREIGN KEY (`IDMUNICIPIO`)
    REFERENCES `bd_medico`.`MUNICIPIO` (`IDMUNICIPIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_ESTADO1`
    FOREIGN KEY (`IDESTADO`)
    REFERENCES `bd_medico`.`ESTADO` (`IDESTADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_OCUPACION1`
    FOREIGN KEY (`IDOCUPACION`)
    REFERENCES `bd_medico`.`OCUPACION` (`IDOCUPACION`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_TIPO_PACIENTE1`
    FOREIGN KEY (`IDTIPO_PACIENTE`)
    REFERENCES `bd_medico`.`TIPO_PACIENTE` (`IDTIPO_PACIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_COLONIA1`
    FOREIGN KEY (`IDCOLONIA`)
    REFERENCES `bd_medico`.`COLONIA` (`IDCOLONIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`HISTORIA_CLINICA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`HISTORIA_CLINICA` (
  `ID_HISTORIA_CLINICA` INT NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA TABLA',
  `IDPACIENTE` INT NOT NULL,
  `FECHA_ALTA` DATE NOT NULL COMMENT 'FECHA DE ALTA COMO PACIENTE',
  `ESTATURA` FLOAT NOT NULL COMMENT 'ESTATURA DEL PACIENTE',
  PRIMARY KEY (`ID_HISTORIA_CLINICA`),
  INDEX `fk_HISTORIA_CLINICA_PACIENTE1_idx` (`IDPACIENTE` ASC),
  CONSTRAINT `fk_HISTORIA_CLINICA_PACIENTE1`
    FOREIGN KEY (`IDPACIENTE`)
    REFERENCES `bd_medico`.`PACIENTE` (`IDPACIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`ALERGIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`ALERGIA` (
  `IDALERGIA` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE_ALERGIA` VARCHAR(50) NOT NULL COMMENT 'NOMBRE DE LA ALERGIA',
  PRIMARY KEY (`IDALERGIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`FACTURA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`FACTURA` (
  `IDFACTURA` INT NOT NULL COMMENT 'CORRESPONDE AL FOLIO DE LA FACTURA, NO ES AUTOINCREMENTABLE Y SE PUEDE REPETIR, YA QUE CADA AÑO SE PUEDE REINICIAR',
  `FECHA` DATE NOT NULL COMMENT 'FECHA DE EXPEDICION DE LA FACTURA',
  `IDPACIENTE` INT NOT NULL,
  INDEX `fk_FACTURA_PACIENTE1_idx` (`IDPACIENTE` ASC),
  CONSTRAINT `fk_FACTURA_PACIENTE1`
    FOREIGN KEY (`IDPACIENTE`)
    REFERENCES `bd_medico`.`PACIENTE` (`IDPACIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`CIRUGIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`CIRUGIA` (
  `IDCIRUGIA` INT NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA TABLA',
  `CIRUGIA` VARCHAR(50) NOT NULL COMMENT 'NOMBRE DE LA CIRUGIA',
  PRIMARY KEY (`IDCIRUGIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`ENFERMEDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`ENFERMEDAD` (
  `IDENFERMEDAD` INT NOT NULL AUTO_INCREMENT,
  `ENFERMEDAD` VARCHAR(50) NOT NULL COMMENT 'ENFERMEDAD O PADECIMIENTO',
  PRIMARY KEY (`IDENFERMEDAD`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`HISTORIA_CIRUGIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`HISTORIA_CIRUGIA` (
  `ID_HISTORIA_CLINICA` INT NOT NULL,
  `IDCIRUGIA` INT NOT NULL,
  INDEX `fk_HISTORIA_CLINICA_has_CIRUGIA_CIRUGIA1_idx` (`IDCIRUGIA` ASC),
  INDEX `fk_HISTORIA_CLINICA_has_CIRUGIA_HISTORIA_CLINICA1_idx` (`ID_HISTORIA_CLINICA` ASC),
  CONSTRAINT `fk_HISTORIA_CLINICA_has_CIRUGIA_HISTORIA_CLINICA1`
    FOREIGN KEY (`ID_HISTORIA_CLINICA`)
    REFERENCES `bd_medico`.`HISTORIA_CLINICA` (`ID_HISTORIA_CLINICA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HISTORIA_CLINICA_has_CIRUGIA_CIRUGIA1`
    FOREIGN KEY (`IDCIRUGIA`)
    REFERENCES `bd_medico`.`CIRUGIA` (`IDCIRUGIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`HISTORIA_ENFERMEDAD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`HISTORIA_ENFERMEDAD` (
  `ID_HISTORIA_CLINICA` INT NOT NULL,
  `IDENFERMEDAD` INT NOT NULL,
  INDEX `fk_HISTORIA_CLINICA_has_ENFERMEDAD_ENFERMEDAD1_idx` (`IDENFERMEDAD` ASC),
  INDEX `fk_HISTORIA_CLINICA_has_ENFERMEDAD_HISTORIA_CLINICA1_idx` (`ID_HISTORIA_CLINICA` ASC),
  CONSTRAINT `fk_HISTORIA_CLINICA_has_ENFERMEDAD_HISTORIA_CLINICA1`
    FOREIGN KEY (`ID_HISTORIA_CLINICA`)
    REFERENCES `bd_medico`.`HISTORIA_CLINICA` (`ID_HISTORIA_CLINICA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HISTORIA_CLINICA_has_ENFERMEDAD_ENFERMEDAD1`
    FOREIGN KEY (`IDENFERMEDAD`)
    REFERENCES `bd_medico`.`ENFERMEDAD` (`IDENFERMEDAD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`CITA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`CITA` (
  `IDCITA` INT NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA',
  `IDPACIENTE` INT NOT NULL,
  `FECHA_CITA` DATE NOT NULL COMMENT 'FECHA DE LA CITA',
  `SINTOMAS` VARCHAR(100) NOT NULL COMMENT 'SINTOMAS QUE PRESENTA EL PACIENTE',
  `DIAGNOSTICO` VARCHAR(100) NULL COMMENT 'DIAGNOSTICO DEL MEDICO, PUEDE ESTAR VACIO PORQUE SE GENERA EN UNA CITA POSTERIOR',
  `FECHA_DIAGNOSTICO` DATE NULL COMMENT 'FECHA DEL DIAGNOSTICO',
  `FECHA_PROX_CITA` DATE NULL DEFAULT '1900-01-01' COMMENT 'FECHA DE LA PROXIMA CITA, PUEDE QUEDAR VACIA',
  `PAGO` INT NULL DEFAULT 0 COMMENT 'MONTO PAGADO POR EL PACIENTE',
  `PRESION_ARTERIAL` VARCHAR(7) NULL DEFAULT '000/000' COMMENT 'PRESION ARTERIAL',
  `TEMPERATURA` INT NULL DEFAULT 0 COMMENT 'TEMPERATURA',
  `OXIGENACION` INT NULL DEFAULT 0 COMMENT 'OXIGENACION',
  `PESO` FLOAT NULL DEFAULT 0 COMMENT 'PESO EN KILOGRAMOS',
  PRIMARY KEY (`IDCITA`),
  INDEX `fk_CITA_PACIENTE1_idx` (`IDPACIENTE` ASC),
  CONSTRAINT `fk_CITA_PACIENTE1`
    FOREIGN KEY (`IDPACIENTE`)
    REFERENCES `bd_medico`.`PACIENTE` (`IDPACIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`MEDICAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`MEDICAMENTO` (
  `IDMEDICAMENTO` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(100) NOT NULL COMMENT 'NOMBRE DEL MEDICAMENTO',
  PRIMARY KEY (`IDMEDICAMENTO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`CITA_MEDICAMENTO_NUEVO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`CITA_MEDICAMENTO_NUEVO` (
  `IDCITA` INT NOT NULL,
  `IDMEDICAMENTO` INT NOT NULL,
  INDEX `fk_CITA_has_MEDICAMENTO_MEDICAMENTO1_idx` (`IDMEDICAMENTO` ASC),
  INDEX `fk_CITA_has_MEDICAMENTO_CITA1_idx` (`IDCITA` ASC),
  CONSTRAINT `fk_CITA_has_MEDICAMENTO_CITA1`
    FOREIGN KEY (`IDCITA`)
    REFERENCES `bd_medico`.`CITA` (`IDCITA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CITA_has_MEDICAMENTO_MEDICAMENTO1`
    FOREIGN KEY (`IDMEDICAMENTO`)
    REFERENCES `bd_medico`.`MEDICAMENTO` (`IDMEDICAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`CITA_MEDICAMENTO_ANTERIOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`CITA_MEDICAMENTO_ANTERIOR` (
  `IDCITA` INT NOT NULL,
  `IDMEDICAMENTO` INT NOT NULL,
  INDEX `fk_CITA_has_MEDICAMENTO_MEDICAMENTO2_idx` (`IDMEDICAMENTO` ASC),
  INDEX `fk_CITA_has_MEDICAMENTO_CITA2_idx` (`IDCITA` ASC),
  CONSTRAINT `fk_CITA_has_MEDICAMENTO_CITA2`
    FOREIGN KEY (`IDCITA`)
    REFERENCES `bd_medico`.`CITA` (`IDCITA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CITA_has_MEDICAMENTO_MEDICAMENTO2`
    FOREIGN KEY (`IDMEDICAMENTO`)
    REFERENCES `bd_medico`.`MEDICAMENTO` (`IDMEDICAMENTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`ESTUDIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`ESTUDIO` (
  `IDESTUDIO` INT NOT NULL AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA',
  `NOMBRE_ESTUDIO` VARCHAR(100) NOT NULL COMMENT 'NOMBRE DEL ESTUDIO',
  PRIMARY KEY (`IDESTUDIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`CITA_ESTUDIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`CITA_ESTUDIO` (
  `IDCITA` INT NOT NULL,
  `IDESTUDIO` INT NOT NULL,
  INDEX `fk_CITA_has_ESTUDIO_ESTUDIO1_idx` (`IDESTUDIO` ASC),
  INDEX `fk_CITA_has_ESTUDIO_CITA1_idx` (`IDCITA` ASC),
  CONSTRAINT `fk_CITA_has_ESTUDIO_CITA1`
    FOREIGN KEY (`IDCITA`)
    REFERENCES `bd_medico`.`CITA` (`IDCITA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CITA_has_ESTUDIO_ESTUDIO1`
    FOREIGN KEY (`IDESTUDIO`)
    REFERENCES `bd_medico`.`ESTUDIO` (`IDESTUDIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_medico`.`HISTORIA_ALERGIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_medico`.`HISTORIA_ALERGIA` (
  `ID_HISTORIA_CLINICA` INT NOT NULL,
  `IDALERGIA` INT NOT NULL,
  INDEX `fk_HISTORIA_CLINICA_has_ALERGIA_ALERGIA1_idx` (`IDALERGIA` ASC),
  INDEX `fk_HISTORIA_CLINICA_has_ALERGIA_HISTORIA_CLINICA1_idx` (`ID_HISTORIA_CLINICA` ASC),
  CONSTRAINT `fk_HISTORIA_CLINICA_has_ALERGIA_HISTORIA_CLINICA1`
    FOREIGN KEY (`ID_HISTORIA_CLINICA`)
    REFERENCES `bd_medico`.`HISTORIA_CLINICA` (`ID_HISTORIA_CLINICA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HISTORIA_CLINICA_has_ALERGIA_ALERGIA1`
    FOREIGN KEY (`IDALERGIA`)
    REFERENCES `bd_medico`.`ALERGIA` (`IDALERGIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
