USE bd_medico

CREATE TABLE POBLACION (
  IDPOBLACION INT NOT NULL IDENTITY(1,1),
  NOMBRE_POBLACION VARCHAR(50) NOT NULL,
  PRIMARY KEY (IDPOBLACION));

CREATE TABLE  MUNICIPIO (
  IDMUNICIPIO INT NOT NULL IDENTITY(1,1),
  NOMBRE_MUNICIPIO VARCHAR(50) NOT NULL,
  PRIMARY KEY (IDMUNICIPIO));


CREATE TABLE  COLONIA (
  IDCOLONIA INT NOT NULL IDENTITY(1,1),
  NOMBRE_COLONIA VARCHAR(100) NOT NULL,
  PRIMARY KEY (IDCOLONIA));


CREATE TABLE  ESTADO (
  IDESTADO INT NOT NULL IDENTITY(1,1),
  NOMBRE_ESTADO VARCHAR(30) NOT NULL,
  PRIMARY KEY (IDESTADO));

  CREATE TABLE  OCUPACION (
  IDOCUPACION INT NOT NULL IDENTITY(1,1),
  NOMBRE_OCUPACION VARCHAR(50) NOT NULL,
  PRIMARY KEY (IDOCUPACION));

CREATE TABLE  TIPO_PACIENTE (
  IDTIPO_PACIENTE INT NOT NULL IDENTITY(1,1),
  TIPO_PACIENTE VARCHAR(20) NOT NULL,
  PRIMARY KEY (IDTIPO_PACIENTE));

CREATE TABLE  PACIENTE (
  IDPACIENTE INT NOT NULL IDENTITY(1,1),
  NOMBRES VARCHAR(30) NOT NULL,
  APATERNO VARCHAR(20) NOT NULL,
  AMATERNO VARCHAR(20) NOT NULL,
  CALLE VARCHAR(100) NOT NULL,
  NUMERO INT NOT NULL,
  FECHA_NACIMIENTO DATE NOT NULL DEFAULT '1900-01-01',
  TEL_FIJO VARCHAR(10) NULL ,
  TEL_TRABAJO VARCHAR(10) NULL,
  TEL_CELULAR VARCHAR(10) NOT NULL,
  SEXO CHAR(1) NOT NULL,
  EMAIL VARCHAR(100) NULL DEFAULT 'correo@algo.com',
  RFC VARCHAR(13) NULL DEFAULT 'ALGO000000XXX',
  FECHA_ALTA DATE NOT NULL,
  ESTATUS CHAR(1) NOT NULL DEFAULT 'A',
  IDPOBLACION INT NOT NULL,
  IDMUNICIPIO INT NOT NULL,
  IDCOLONIA INT NOT NULL,
  IDESTADO INT NOT NULL,
  IDOCUPACION INT NOT NULL,
  IDTIPO_PACIENTE INT NOT NULL,
  PRIMARY KEY (IDPACIENTE),
  INDEX fk_PACIENTE_POBLACION1_idx (IDPOBLACION ASC),
  INDEX fk_PACIENTE_MUNICIPIO1_idx (IDMUNICIPIO ASC),
  INDEX fk_PACIENTE_COLONIA1_idx (IDCOLONIA ASC),
  INDEX fk_PACIENTE_ESTADO1_idx (IDESTADO ASC),
  INDEX fk_PACIENTE_OCUPACION1_idx (IDOCUPACION ASC),
  INDEX fk_PACIENTE_TIPO_PACIENTE1_idx (IDTIPO_PACIENTE ASC),
  CONSTRAINT PACIENTE_POBLACION
    FOREIGN KEY (IDPOBLACION)
    REFERENCES POBLACION (IDPOBLACION)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT PACIENTE_MUNICIPIO
    FOREIGN KEY (IDMUNICIPIO)
    REFERENCES MUNICIPIO (IDMUNICIPIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT PACIENTE_COLONIA
    FOREIGN KEY (IDCOLONIA)
    REFERENCES COLONIA (IDCOLONIA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT PACIENTE_ESTADO
    FOREIGN KEY (IDESTADO)
    REFERENCES ESTADO (IDESTADO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT PACIENTE_OCUPACION
    FOREIGN KEY (IDOCUPACION)
    REFERENCES OCUPACION (IDOCUPACION)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT PACIENTE_TIPO_PACIENTE
    FOREIGN KEY (IDTIPO_PACIENTE)
    REFERENCES TIPO_PACIENTE (IDTIPO_PACIENTE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE  HISTORIA_CLINICA (
  ID_HISTORIA_CLINICA INT NOT NULL IDENTITY(1,1),
  IDPACIENTE INT NOT NULL,
  FECHA_ALTA DATE NOT NULL,
  ESTATURA FLOAT NOT NULL,
  PRIMARY KEY (ID_HISTORIA_CLINICA),
  INDEX fk_HISTORIA_CLINICA_PACIENTE1_idx (IDPACIENTE ASC),
  CONSTRAINT fk_HISTORIA_CLINICA_PACIENTE1
    FOREIGN KEY (IDPACIENTE)
    REFERENCES PACIENTE (IDPACIENTE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE  ALERGIA (
  IDALERGIA INT NOT NULL IDENTITY(1,1),
  NOMBRE_ALERGIA VARCHAR(50) NOT NULL,
  PRIMARY KEY (IDALERGIA));


CREATE TABLE  HISTORIA_ALERGIA (
  ID_HISTORIA_CLINICA INT NOT NULL,
  IDALERGIA INT NOT NULL,
  INDEX fk_HISTORIA_CLINICA_has_ALERGIA_ALERGIA1_idx (IDALERGIA ASC),
  INDEX fk_HISTORIA_CLINICA_has_ALERGIA_HISTORIA_CLINICA1_idx (ID_HISTORIA_CLINICA ASC),
  CONSTRAINT fk_HISTORIA_CLINICA_has_ALERGIA_HISTORIA_CLINICA1
    FOREIGN KEY (ID_HISTORIA_CLINICA)
    REFERENCES HISTORIA_CLINICA (ID_HISTORIA_CLINICA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_HISTORIA_CLINICA_has_ALERGIA_ALERGIA1
    FOREIGN KEY (IDALERGIA)
    REFERENCES ALERGIA (IDALERGIA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE  FACTURA (
  IDFACTURA INT NOT NULL,
  FECHA DATE NOT NULL,
  IDPACIENTE INT NOT NULL,
  INDEX fk_FACTURA_PACIENTE1_idx (IDPACIENTE ASC),
  CONSTRAINT fk_FACTURA_PACIENTE1
    FOREIGN KEY (IDPACIENTE)
    REFERENCES PACIENTE (IDPACIENTE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE  CIRUGIA (
  IDCIRUGIA INT NOT NULL IDENTITY(1,1),
  CIRUGIA VARCHAR(50) NOT NULL,
  PRIMARY KEY (IDCIRUGIA));


CREATE TABLE  ENFERMEDAD (
  IDENFERMEDAD INT NOT NULL IDENTITY(1,1),
  ENFERMEDAD VARCHAR(50) NOT NULL,
  PRIMARY KEY (IDENFERMEDAD));

CREATE TABLE  HISTORIA_CIRUGIA (
  ID_HISTORIA_CLINICA INT NOT NULL,
  IDCIRUGIA INT NOT NULL,
  INDEX fk_HISTORIA_CLINICA_has_CIRUGIA_CIRUGIA1_idx (IDCIRUGIA ASC),
  INDEX fk_HISTORIA_CLINICA_has_CIRUGIA_HISTORIA_CLINICA1_idx (ID_HISTORIA_CLINICA ASC),
  CONSTRAINT fk_HISTORIA_CLINICA_has_CIRUGIA_HISTORIA_CLINICA1
    FOREIGN KEY (ID_HISTORIA_CLINICA)
    REFERENCES HISTORIA_CLINICA (ID_HISTORIA_CLINICA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_HISTORIA_CLINICA_has_CIRUGIA_CIRUGIA1
    FOREIGN KEY (IDCIRUGIA)
    REFERENCES CIRUGIA (IDCIRUGIA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE  HISTORIA_ENFERMEDAD (
  ID_HISTORIA_CLINICA INT NOT NULL,
  IDENFERMEDAD INT NOT NULL,
  INDEX fk_HISTORIA_CLINICA_has_ENFERMEDAD_ENFERMEDAD1_idx (IDENFERMEDAD ASC),
  INDEX fk_HISTORIA_CLINICA_has_ENFERMEDAD_HISTORIA_CLINICA1_idx (ID_HISTORIA_CLINICA ASC),
  CONSTRAINT fk_HISTORIA_CLINICA_has_ENFERMEDAD_HISTORIA_CLINICA1
    FOREIGN KEY (ID_HISTORIA_CLINICA)
    REFERENCES HISTORIA_CLINICA (ID_HISTORIA_CLINICA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_HISTORIA_CLINICA_has_ENFERMEDAD_ENFERMEDAD1
    FOREIGN KEY (IDENFERMEDAD)
    REFERENCES ENFERMEDAD (IDENFERMEDAD)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE  CITA (
  IDCITA INT NOT NULL IDENTITY(1,1),
  IDPACIENTE INT NOT NULL,
  FECHA_CITA DATE NOT NULL,
  SINTOMAS VARCHAR(100) NOT NULL,
  DIAGNOSTICO VARCHAR(100) NULL,
  FECHA_DIAGNOSTICO DATE NULL,
  FECHA_PROX_CITA DATE NULL DEFAULT '1900-01-01',
  PAGO INT NULL DEFAULT 0,
  PRESION_ARTERIAL VARCHAR(7) NULL DEFAULT '000/000',
  TEMPERATURA INT NULL DEFAULT 0,
  OXIGENACION INT NULL DEFAULT 0,
  PESO FLOAT NULL DEFAULT 0,
  PRIMARY KEY (IDCITA),
  INDEX fk_CITA_PACIENTE1_idx (IDPACIENTE ASC),
  CONSTRAINT fk_CITA_PACIENTE1
    FOREIGN KEY (IDPACIENTE)
    REFERENCES PACIENTE (IDPACIENTE)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

	CREATE TABLE  MEDICAMENTO (
  IDMEDICAMENTO INT NOT NULL IDENTITY(1,1),
  NOMBRE VARCHAR(100) NOT NULL,
  PRIMARY KEY (IDMEDICAMENTO));


CREATE TABLE  CITA_MEDICAMENTO_NUEVO (
  IDCITA INT NOT NULL,
  IDMEDICAMENTO INT NOT NULL,
  INDEX fk_CITA_has_MEDICAMENTO_MEDICAMENTO1_idx (IDMEDICAMENTO ASC),
  INDEX fk_CITA_has_MEDICAMENTO_CITA1_idx (IDCITA ASC),
  CONSTRAINT fk_CITA_has_MEDICAMENTO_CITA1
    FOREIGN KEY (IDCITA)
    REFERENCES CITA (IDCITA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_CITA_has_MEDICAMENTO_MEDICAMENTO1
    FOREIGN KEY (IDMEDICAMENTO)
    REFERENCES MEDICAMENTO (IDMEDICAMENTO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE  CITA_MEDICAMENTO_ANTERIOR (
  IDCITA INT NOT NULL,
  IDMEDICAMENTO INT NOT NULL,
  INDEX fk_CITA_has_MEDICAMENTO_MEDICAMENTO2_idx (IDMEDICAMENTO ASC),
  INDEX fk_CITA_has_MEDICAMENTO_CITA2_idx (IDCITA ASC),
  CONSTRAINT fk_CITA_has_MEDICAMENTO_CITA2
    FOREIGN KEY (IDCITA)
    REFERENCES CITA (IDCITA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_CITA_has_MEDICAMENTO_MEDICAMENTO2
    FOREIGN KEY (IDMEDICAMENTO)
    REFERENCES MEDICAMENTO (IDMEDICAMENTO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE  ESTUDIO (
  IDESTUDIO INT NOT NULL IDENTITY(1,1),
  NOMBRE_ESTUDIO VARCHAR(100) NOT NULL,
  PRIMARY KEY (IDESTUDIO));


CREATE TABLE  CITA_ESTUDIO (
  IDCITA INT NOT NULL,
  IDESTUDIO INT NOT NULL,
  INDEX fk_CITA_has_ESTUDIO_ESTUDIO1_idx (IDESTUDIO ASC),
  INDEX fk_CITA_has_ESTUDIO_CITA1_idx (IDCITA ASC),
  CONSTRAINT fk_CITA_has_ESTUDIO_CITA1
    FOREIGN KEY (IDCITA)
    REFERENCES CITA (IDCITA)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_CITA_has_ESTUDIO_ESTUDIO1
    FOREIGN KEY (IDESTUDIO)
    REFERENCES ESTUDIO (IDESTUDIO)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


