CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_ConsultarCita`(in idCit int)
BEGIN
	SELECT CITA.IDCITA, PACIENTE.IDPACIENTE,CONCAT(NOMBRES,' ',APATERNO,' ',AMATERNO) AS NOMBRE,FECHA_CITA, SINTOMAS, DIAGNOSTICO, FECHA_DIAGNOSTICO, FECHA_PROX_CITA, PAGO, PRESION_ARTERIAL, TEMPERATURA, OXIGENACION, PESO 
	FROM PACIENTE INNER JOIN CITA ON PACIENTE.IDPACIENTE = CITA.IDPACIENTE
	where CITA.IDCITA = idCit;
END