CREATE DEFINER=`root`@`localhost` PROCEDURE `sp_ConsultarPaciente`(in idPac int)
BEGIN
	SELECT PACIENTE.IDPACIENTE, NOMBRES, APATERNO, AMATERNO, NOMBRE_COLONIA, CALLE, NUMERO, NOMBRE_ESTADO, NOMBRE_MUNICIPIO, NOMBRE_POBLACION, FECHA_NACIMIENTO, TEL_FIJO, TEL_TRABAJO, TEL_CELULAR, SEXO, EMAIL, RFC, NOMBRE_OCUPACION, FECHA_ALTA, TIPO_PACIENTE, ESTATUS
	FROM PACIENTE INNER JOIN POBLACION ON PACIENTE.IDPOBLACION = POBLACION.IDPOBLACION
	INNER JOIN MUNICIPIO ON PACIENTE.IDMUNICIPIO = MUNICIPIO.IDMUNICIPIO
	INNER JOIN COLONIA ON PACIENTE.IDCOLONIA = COLONIA.IDCOLONIA
	INNER JOIN ESTADO ON PACIENTE.IDESTADO = ESTADO.IDESTADO
	INNER JOIN OCUPACION ON PACIENTE.IDOCUPACION = OCUPACION.IDOCUPACION
	INNER JOIN TIPO_PACIENTE ON PACIENTE.IDTIPO_PACIENTE = TIPO_PACIENTE.IDTIPO_PACIENTE
	WHERE IDPACIENTE = idPac;
END